### ISSUE TITLE
Question....

### ISSUE THREAD

**Issue by sahhas16** [MrAugu/simple-discordjs-dashboard#3]
How do I intergrate this with my website. If i wrote something not in format, pls message her and don't close.

**Comment by AtaraxiaPlayz** [comment]
It depends on how you wrote your website. You may be able to change certain paths (I certainly don’t have the expertise in that) and where they lead to. Skimming the [EJS website](https://ejs.co/) might help you with this. Otherwise, this was technically meant to be used as-created and might need a bit of updating.

I hope I (somehow) helped. -Ataraxia

**Comment by MrAugu** [comment]
As @AtaraxiaCodes said, you are able to integrate this only if your website used EJS and express.
